### ISSUE TITLE
some bugs

### ISSUE THREAD

**Issue by user597** [fuzzylite/fuzzylite#27]
Hello
When I forgot to define A's membership function in the following code, the result was exception without significant error message.
Also, I think it's a good idea to add in the documentation  a list of supported membership functions with parameters (it was difficult for me to guess 
that the two parameters of ZShape were [start .. end], instead of [center .. delta] like in pyfuzzy. In reality, I didn't guess, I was obliged to read ZShape.cpp)  
finally,  comments between (**), on fcl, doesn't work. is there a way to add comments ?  
I don't know  "OR:MAX;"  doesn't work and I must use "OR : MAX;" ? 
I didn't explore your code yet ( I'm too busy this days :( ), but I don't think that a syntactical parser (like YACC) is used inside. 
if it is true, it's a good true to think about it. Adding this features will be easier.

I have a question about license, If I use your software as shared library, is that allowed ? 
```
FUNCTION_BLOCK IMP
    VAR_INPUT
        A :  REAL;
    END_VAR
    VAR_OUTPUT
         RES : REAL;
    END_VAR

    FUZZIFY A
        RANGE := (0.000 .. 1.000);
        TERM  CRTE:=  ;
    END_FUZZIFY


    DEFUZZIFY RES
        RANGE :=(0.000..100.00)
        TERM B:= 0;
        TERM M:= 1;
        TERM H:= 100;
        DEFAULT := 0;
        METHOD : COGS;
    END_DEFUZZIFY

    RULEBLOCK first
        OR : MAX;
        AND : MIN;
        RULE 0: if A is CRTE then  RES is B;
    END_RULEBLOCK

END_FUNCTION_BLOCK
```

```bash
~$./fuzzylite -i test1.fcl -o a.cpp
/src/Exception.cpp [173]:[unexpected signal 11] Segmentation fault
BACKTRACE:
/usr/lib/libfuzzylite.so.5.0(_ZN2fl9Exception11btCallStackEv+0x196) [0x7f66c61e45a6]
/usr/lib/libfuzzylite.so.5.0(_ZN2fl9Exception13signalHandlerEi+0x1dc) [0x7f66c61e5dfc]
/lib/x86_64-linux-gnu/libc.so.6(+0x36d40) [0x7f66c5afad40]
/usr/lib/libfuzzylite.so.5.0(_ZNK2fl11FclImporter9parseTermERKSsPKNS_6EngineE+0x798) [0x7f66c62140c8]
/usr/lib/libfuzzylite.so.5.0(_ZNK2fl11FclImporter14processFuzzifyERKSsPNS_6EngineE+0x733) [0x7f66c620e5d3]
/usr/lib/libfuzzylite.so.5.0(_ZNK2fl11FclImporter12processBlockERKSsS2_PNS_6EngineE+0xc7) [0x7f66c6207217]
/usr/lib/libfuzzylite.so.5.0(_ZNK2fl11FclImporter10fromStringERKSs+0x1be1) [0x7f66c6211b91]
/usr/lib/libfuzzylite.so.5.0(_ZN2fl7Console7processERKSsRSoS2_S2_RKSt3mapISsSsSt4lessISsESaISt4pairIS1_SsEEE+0xa5) [0x7f66c61c8255]
/usr/lib/libfuzzylite.so.5.0(_ZN2fl7Console7processERKSt3mapISsSsSt4lessISsESaISt4pairIKSsSsEEE+0x508) [0x7f66c61c99a8]
/usr/lib/libfuzzylite.so.5.0(_ZN2fl7Console4mainEiPPc+0x43) [0x7f66c61be4a3]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7f66c5ae5ec5]
./fuzzylite() [0x400b80]

{at /src/Exception.cpp::signalHandler() [line:141]}

BACKTRACE:
/usr/lib/libfuzzylite.so.5.0(_ZN2fl9Exception11btCallStackEv+0x196) [0x7f66c61e45a6]
/usr/lib/libfuzzylite.so.5.0(_ZN2fl9Exception14catchExceptionERKSt9exception+0x195) [0x7f66c61e54d5]
/usr/lib/libfuzzylite.so.5.0(_ZN2fl9Exception13signalHandlerEi+0x36e) [0x7f66c61e5f8e]
/lib/x86_64-linux-gnu/libc.so.6(+0x36d40) [0x7f66c5afad40]
/usr/lib/libfuzzylite.so.5.0(_ZNK2fl11FclImporter9parseTermERKSsPKNS_6EngineE+0x798) [0x7f66c62140c8]
/usr/lib/libfuzzylite.so.5.0(_ZNK2fl11FclImporter14processFuzzifyERKSsPNS_6EngineE+0x733) [0x7f66c620e5d3]
/usr/lib/libfuzzylite.so.5.0(_ZNK2fl11FclImporter12processBlockERKSsS2_PNS_6EngineE+0xc7) [0x7f66c6207217]
/usr/lib/libfuzzylite.so.5.0(_ZNK2fl11FclImporter10fromStringERKSs+0x1be1) [0x7f66c6211b91]
/usr/lib/libfuzzylite.so.5.0(_ZN2fl7Console7processERKSsRSoS2_S2_RKSt3mapISsSsSt4lessISsESaISt4pairIS1_SsEEE+0xa5) [0x7f66c61c8255]
/usr/lib/libfuzzylite.so.5.0(_ZN2fl7Console7processERKSt3mapISsSsSt4lessISsESaISt4pairIKSsSsEEE+0x508) [0x7f66c61c99a8]
/usr/lib/libfuzzylite.so.5.0(_ZN2fl7Console4mainEiPPc+0x43) [0x7f66c61be4a3]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7f66c5ae5ec5]
./fuzzylite() [0x400b80]
```

**Comment by jcrada** [comment]
Hi, thank you for your post.

(1) fuzzylite is a different library from pyfuzzy, so we do things differently. Unfortunately, there is no documentation available at the moment, but the source code is fairly easy to follow. Considering that you are using the library, it will be necessary to read the code to find out what the parameters are. However, you can always use QtFuzzyLite, which will help you design your controllers and offer you more information on the parameters for each term. Please, visit www.fuzzylite.com/downloads .

(2) Comments in my implementation of FCL are defined by `#` or `//`. Comments are *not* multi-line. Each comment starts and ends in a single line. Please, revise the FuzzyLite Language (FLL), which is much simpler and better than the FCL. Visit www.fuzzylite.com/fll-fld/ .

(3) I developed my own parsers to process the different formats. These parsers are much simpler than utilizing a third-party library, but they expect to receive a properly formatted code. I prefer not to depend on third-party libraries to process these files. Tokenization is often used in the Importers, and generally utilizing `std::istringstream`, which tokenizes based on whitespaces (`'\t'`, `' '`). Having said this, `OR : MAX` should work. QtFuzzyLite will show you an FCL template upon importing an Engine. For more information, please revise `src/FclExporter` and `src/FclImporter`.

(4) fuzzylite is dual licensed under the GNU Lesser General Public License (LGPL) and a commercial license. You may use fuzzylite commercially free of charge as long as you use it as a dynamic library and comply with the LGPL requirements. 

(5) The error in the example is not meaningful because it produces a Segmentation Fault. I will further revise this part to ensure an exception is thrown with an appropriate message.

**Comment by jcrada** [comment]
I have updated `master` branch to provide more information upon the error you were experiencing. Thank you.
