### ISSUE TITLE
is scalar and float interchangeable ?

### ISSUE THREAD

**Issue by user597** [fuzzylite/fuzzylite#28]
hello 
Can I use float instead  of scalar in input variables ? 
I tried it and it works. I want to know in which cases It doesn't work ?
If they are interchangeable so, why using non-standard type ?

**Comment by jcrada** [comment]
Hi,

in `fl/fuzzylite.h`, you will see that `fl::scalar` is a double. The reason to prefer `fl::scalar` is that you can compile fuzzylite using either `float` or `double` precision. If you prefer fuzzylite to use `float` instead of `double`, please visit http://www.fuzzylite.com/cpp/#Advanced_building_options
